// <auto-generated />
using System;
using Basisregisters.FeedConsumers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Basisregisters.FeedConsumers.Migrations
{
    [DbContext(typeof(FeedContext))]
    [Migration("20260428131807_AddVersionIdAsString")]
    partial class AddVersionIdAsString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.Address", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<string>("BoxNumber")
                        .HasColumnType("text")
                        .HasColumnName("box_number");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house_number");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<bool>("OfficiallyAssigned")
                        .HasColumnType("boolean")
                        .HasColumnName("officially_assigned");

                    b.Property<int>("PersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("persistent_local_id");

                    b.Property<string>("PositionMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_method");

                    b.Property<string>("PositionSpecification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_specification");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StreetNamePersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("street_name_persistent_local_id");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.HasIndex("BoxNumber");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("HouseNumber");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("PersistentLocalId");

                    b.HasIndex("PostalCode");

                    b.HasIndex("Status");

                    b.HasIndex("StreetNamePersistentLocalId");

                    b.HasIndex("IsRemoved", "Status");

                    b.ToTable("addresses", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.Building", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geometry");

                    b.Property<string>("GeometryMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geometry_method");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<int>("PersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("persistent_local_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("PersistentLocalId");

                    b.HasIndex("Status");

                    b.ToTable("buildings", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.BuildingUnit", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<int>("BuildingPersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("building_persistent_local_id");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("function");

                    b.Property<string>("GeometryMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geometry_method");

                    b.Property<bool>("HasDeviation")
                        .HasColumnType("boolean")
                        .HasColumnName("has_deviation");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<int>("PersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("persistent_local_id");

                    b.Property<Geometry>("Position")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("position");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.HasIndex("BuildingPersistentLocalId");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("PersistentLocalId");

                    b.HasIndex("Position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "GIST");

                    b.HasIndex("Status");

                    b.ToTable("buildingunits", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.BuildingUnitAddress", b =>
                {
                    b.Property<int>("BuildingUnitPersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("buildingunit_persistent_local_id");

                    b.Property<int>("AddressPersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("address_persistent_local_id");

                    b.HasKey("BuildingUnitPersistentLocalId", "AddressPersistentLocalId");

                    b.HasIndex("AddressPersistentLocalId");

                    b.HasIndex("BuildingUnitPersistentLocalId");

                    b.ToTable("buildingunit_addresses", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.FeedState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("EventPosition")
                        .HasColumnType("bigint")
                        .HasColumnName("event_position");

                    b.Property<int>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.HasKey("Name");

                    b.ToTable("feed_states", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.Municipality", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<bool?>("FacilityLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_dutch");

                    b.Property<bool?>("FacilityLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_english");

                    b.Property<bool?>("FacilityLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_french");

                    b.Property<bool?>("FacilityLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_german");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<string>("NameDutch")
                        .HasColumnType("text")
                        .HasColumnName("name_dutch");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("text")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .HasColumnType("text")
                        .HasColumnName("name_french");

                    b.Property<string>("NameGerman")
                        .HasColumnType("text")
                        .HasColumnName("name_german");

                    b.Property<string>("NisCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nis_code");

                    b.Property<bool?>("OfficialLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_dutch");

                    b.Property<bool?>("OfficialLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_english");

                    b.Property<bool?>("OfficialLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_french");

                    b.Property<bool?>("OfficialLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_german");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.ToTable("municipalities", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.Parcel", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<string>("CaPaKey")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("capakey");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VbrCaPaKey")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("vbr_capakey");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.ToTable("parcels", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.ParcelAddress", b =>
                {
                    b.Property<string>("VbrCaPaKey")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("vbr_capakey");

                    b.Property<int>("AddressPersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("address_persistent_local_id");

                    b.HasKey("VbrCaPaKey", "AddressPersistentLocalId");

                    b.HasIndex("AddressPersistentLocalId");

                    b.HasIndex("VbrCaPaKey");

                    b.ToTable("parcel_addresses", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.PostalInformation", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<string>("NisCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nis_code");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.HasIndex("NisCode");

                    b.HasIndex("PostalCode")
                        .IsUnique();

                    b.ToTable("postal_information", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.PostalInformationName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.HasKey("Id");

                    b.HasIndex("PostalCode");

                    b.ToTable("postal_information_name", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.StreetName", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<string>("HomonymAdditionDutch")
                        .HasColumnType("text")
                        .HasColumnName("homonym_addition_dutch");

                    b.Property<string>("HomonymAdditionEnglish")
                        .HasColumnType("text")
                        .HasColumnName("homonym_addition_english");

                    b.Property<string>("HomonymAdditionFrench")
                        .HasColumnType("text")
                        .HasColumnName("homonym_addition_french");

                    b.Property<string>("HomonymAdditionGerman")
                        .HasColumnType("text")
                        .HasColumnName("homonym_addition_german");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<string>("NameDutch")
                        .HasColumnType("text")
                        .HasColumnName("name_dutch");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("text")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .HasColumnType("text")
                        .HasColumnName("name_french");

                    b.Property<string>("NameGerman")
                        .HasColumnType("text")
                        .HasColumnName("name_german");

                    b.Property<string>("NisCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nis_code");

                    b.Property<int>("PersistentLocalId")
                        .HasColumnType("integer")
                        .HasColumnName("persistent_local_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.Property<string>("VersionIdAsString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_id_as_string");

                    b.HasKey("PersistentUri");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("NisCode");

                    b.HasIndex("PersistentLocalId");

                    b.HasIndex("Status");

                    b.ToTable("streetnames", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.PostalInformationName", b =>
                {
                    b.HasOne("Basisregisters.FeedConsumers.Model.PostalInformation", null)
                        .WithMany("PostalNames")
                        .HasForeignKey("PostalCode")
                        .HasPrincipalKey("PostalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.PostalInformation", b =>
                {
                    b.Navigation("PostalNames");
                });
#pragma warning restore 612, 618
        }
    }
}
