// <auto-generated />
using System;
using Basisregisters.FeedConsumers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Basisregisters.FeedConsumers.Migrations
{
    [DbContext(typeof(FeedContext))]
    partial class FeedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.FeedState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("EventPosition")
                        .HasColumnType("bigint")
                        .HasColumnName("event_position");

                    b.Property<int>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.HasKey("Name");

                    b.ToTable("feed_states", "changefeed");
                });

            modelBuilder.Entity("Basisregisters.FeedConsumers.Model.Municipality", b =>
                {
                    b.Property<string>("PersistentUri")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("persistent_uri");

                    b.Property<bool?>("FacilityLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_dutch");

                    b.Property<bool?>("FacilityLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_english");

                    b.Property<bool?>("FacilityLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_french");

                    b.Property<bool?>("FacilityLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("facility_language_german");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<string>("NameDutch")
                        .HasColumnType("text")
                        .HasColumnName("name_dutch");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("text")
                        .HasColumnName("name_english");

                    b.Property<string>("NameFrench")
                        .HasColumnType("text")
                        .HasColumnName("name_french");

                    b.Property<string>("NameGerman")
                        .HasColumnType("text")
                        .HasColumnName("name_german");

                    b.Property<string>("NisCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nis_code");

                    b.Property<bool?>("OfficialLanguageDutch")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_dutch");

                    b.Property<bool?>("OfficialLanguageEnglish")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_english");

                    b.Property<bool?>("OfficialLanguageFrench")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_french");

                    b.Property<bool?>("OfficialLanguageGerman")
                        .HasColumnType("boolean")
                        .HasColumnName("official_language_german");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("VersionId")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("version_id");

                    b.HasKey("PersistentUri");

                    b.ToTable("municipalities", "changefeed");
                });
#pragma warning restore 612, 618
        }
    }
}
